### ISSUE TITLE
協同設計室電腦安裝

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/wcm2019#2]
# UEFI 設定
2019 年寒假換裝電腦輔助繪圖的是電腦, 總共有 4 台放在協同設計室, 這批電腦要安裝 Windows 10 之前, 必須先在 UEFI 中進行設定:

> 而且若要使用 UEFI 介面所提供的 CSM (相容支援模組), Secure Boot 設定必須取消 (disabled).
> 
> Compatibility with legacy BIOS. Some UEFI-based PCs contain a Compatibility Support Module (CSM) that emulates earlier BIOS, providing more flexibility and compatibility for end users. To use the CSM, Secure Boot must be disabled.

# Intel 網路卡驅動程式
Windows 安裝 DVD 下載與操作:
系統安裝後, 必須以其他能上網的電腦, 從 https://downloadcenter.intel.com/download/25016/Intel-Network-Adapter-Driver-for-Windows-10?product=36773 下載網路卡驅動程式, 放入隨身碟後進行安裝.

# 以 IPV6 上網
由於目前已經無 IPv4 位址聯外, 必須採用 IPv6 DHCP 設定上網, DNS server 設為 

2001:288:6004:17::3 (機械設計工程系 DNS server)

與

2001:b000:168::1 (中華電信 DNS server)

並利用 Proxy (http://proxy.kmol.info:3128) , 連結到其他 IPv4 設定電腦.

# 安裝 Virtualbox

https://www.virtualbox.org/

# 安裝 Virtualbox 上的 Ubuntu 18.04

若要讓 Virtualbox 上的 Ubuntu 作為聯外 Server, 網路卡可設為 bridge.

# 設定 Ubuntu /etc/netplan

IPv6 以 cd10 ~ cd13 共四台分別定址, 若有其他固定 IP server, 採 cd20 ~ cd29 定址.

```
network:
    ethernets:
        enp0s3:
            addresses: 
                - 2001:288:6004:17:0811::cd10/64
            gateway6: 2001:288:6004:17::254
            nameservers:
                addresses:
                    - 2001:b000:168::1
 
    version: 2
```
上述網路設定完成後, 以 sudo netplan apply 啟用設定

# apt 代理主機設定

vi /etc/apt/apt.conf, 放入

Acquire::http::Proxy "http://proxy.kmol.info:3128";

之後, 以 

sudo apt update
sudo apt install ubuntu-desktop

安裝 Ubuntu Desktop
